Stop syncing ccx-secrets/ccx-pull-secret
Attempts to use this secret causes:

```console
$ podman pull quay.io/kubevirt/common-templates:latest
Trying to pull quay.io/kubevirt/common-templates:latest...
  unable to retrieve auth token: invalid username/password: unauthorized: Could not find robot with specified username
Error: unable to pull quay.io/kubevirt/common-templates:latest: Error initializing source docker://quay.io/kubevirt/common-templates:latest: unable to retrieve auth token: invalid username/password: unauthorized: Could not find robot with specified username
```