OpenStack: Remove obsolete skips
We're in the process of removing the in-tree cloud provider with the k8s
1.26 rebase, and to do so we had to skip in-tree cinder provisioner
tests with https://github.com/openshift/origin/pull/27613.

This caused the
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.13-e2e-openstack-ovn-appcreds
job to fail with:

    Error: no tests were found matching the TEST_SKIPS regex:
    In-tree Volumes \[Driver: cinder\]

The plan is to revert https://github.com/openshift/origin/pull/27613 as
soon as the 1.26 rebase lands. Drop the obsolete TEST_SKIPS for now
at least until the revert is effective.