Use specific pip installer for RHEL9 SNO AWS conf
We've seen the following error in the rehearsals for this [1] PR:

```
ERROR: This script does not work on Python 3.9. The minimum supported Python version is 3.10. Please use https://bootstrap.pypa.io/pip/3.9/get-pip.py instead.
```

I'm not sure what about the PR is causing this, but looks like it can be
solved by adding the version number to the pip installer download URL.

[1] https://github.com/openshift/release/pull/78300