ci-operator/step-registry/ipi: Drop /tmp/secret mkdirs
Fixing errors like [1]:

  2020/03/12 23:45:35 Container cp-secret-wrapper in pod e2e-steps-ipi-conf completed successfully
  mkdir: cannot create directory '/tmp/secret': File exists
  error: [failed to execute wrapped command: exit status 1]
  2020/03/12 23:45:37 Container ipi-conf in pod e2e-steps-ipi-conf failed, exit code 1, reason Error

I haven't traced this back to see when it broke, but I'd guess some
ci-tools code is now creating /tmp/secret for each container.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/3269/pull-ci-openshift-installer-release-4.4-e2e-steps/138#1:build-log.txt%3A45