update the cli-jq image to be based off of 4.12
the 4.5 release of 'oc' is old and is missing some features.
for example, this does not work:

[root@9eeaa7467a2d /]# oc wait machinesets -n openshift-machine-api ci-op-zf7g5r0z-e5b69-mw2xn-worker-us-east-2b '--for=jsonpath={.status.readyReplicas}=3' --timeout=900s
error: unrecognized condition: "jsonpath={.status.readyReplicas}=3"

that is working in 4.12

Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>