ci-operator/step-registry/gather/aws-console: Pin 4.5 upi-installer
We need both 'oc' and 'aws' for this script.  The upi-installer image
has a complicated history with the 'aws' command:

* openshift/installer@512f93dd30 (images/installer: add image that can
  be used to instal UPI platforms, 2019-03-22, master and release-4.0,
  openshift/installer#1456) added the epel-release and awscli RPMs.

* openshift/installer@c7b7863b42 (image: remove unneeded packages,
  2019-08-13, master and release-4.2, openshift/installer#2206)
  removed the epel-release and awscli RPMs, which were no longer
  avialable.

* openshift/installer@665ba44f45 (Add AWS CLI to UPI image,
  2020-03-13, master and release-4.5, openshift/installer#3292)
  installed 'aws' via curl.

But that means that today the bundled upi-installer has no 'aws' for
4.4 and earlier, leading to errors like [1]:

  Gathering console logs for i-04151362d551668fe
  /bin/bash: line 39: aws: command not found
  error: failed to execute wrapped command: exit status 1
  2020/06/18 23:52:50 Container test in pod e2e-aws-gather-aws-console failed, exit code 1, reason Error

on 4.2.  With this commit I reference the 4.5 image [2,3], because
that has the commands I need, and we don't need anything that's
particularly senstive to the command versions.

[1]: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/382/pull-ci-openshift-cluster-version-operator-release-4.2-e2e-aws/1273733457419177984
[2]: https://github.com/openshift/ci-tools/blob/97d72735a969f11b210806970d523f1b63297905/pkg/webreg/webreg.go#L933-L946
[3]: https://github.com/openshift/ci-tools/blob/97d72735a969f11b210806970d523f1b63297905/pkg/webreg/webreg.go#L1267-L1279