CVO: Use golangci-lint:v2.3.1 in CI
This is to fix

```
Error: can't load config: the Go language version (go1.24) used to build golangci-lint is lower than the targeted Go version (1.25.0)
Failed executing command with error: can't load config: the Go language version (go1.24) used to build golangci-lint is lower than the targeted Go version (1.25.0)
```

from the job [1] after bumping to Go1.25.

[1]. https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-version-operator/1288/pull-ci-openshift-cluster-version-operator-main-lint/2012180966650417152