[knative] don't try to mirror images that are no longer included in release-nightly build
fixes errors in periodic-image-mirroring-knative
```
error: unable to retrieve source image registry.ci.openshift.org/knative/release-nightly by tag kn-plugin-event-test-wathola-forwarder: manifest unknown: manifest unknown
error: unable to retrieve source image registry.ci.openshift.org/knative/release-nightly by tag kn-plugin-event-test-eventshub: manifest unknown: manifest unknown
error: an error occurred during planning
ERROR: Failed to mirror images from /etc/imagemirror/mapping_knative_release-nightly_kn-plugin-event_quay
```