Use CentOS 9 for `ci-tools-build-root`
The outdated version of `nodejs` is causing build failures:

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/3471/pull-ci-openshift-ci-tools-master-unit/1666725215490543616

```console
# podman run --rm -it --entrypoint bash centos:stream8
[root@0b2e7a09da5f /]# dnf install npm && npm install -g typescript
…
npm WARN notsup Unsupported engine for typescript@5.1.3: wanted: {"node":">=14.17"} (current: {"node":"10.23.1","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: typescript@5.1.3
…
[root@0b2e7a09da5f /]# tsc
/usr/local/lib/node_modules/typescript/lib/tsc.js:93
  for (let i = startIndex ?? 0; i < array.length; i++) {
                           ^

SyntaxError: Unexpected token ?
…
```

```console
# podman run --rm -it --entrypoint bash centos:stream9
[root@9fe865da2a3a /]# dnf install npm && npm install -g typescript
…
[root@9fe865da2a3a /]# tsc
Version 5.1.3
…
```