Delete rpmdb lock files after overriding openshift-hyperkube RPM (#35719)
Running an rpm transaction will leave around various lock files in the
rpmdb. This is usually OK, but here we're building an image and we don't
want them in there, so delete them. This is something rpm-ostree does
also in postprocessing during regular tree composes and is probably
something it should learn to do client-side when pulling down a layered
container too. But ideally we'd enforce it at image build time. For now
hack around this here.

More practically, this breaks the bdb backend of libsolv for some reason,
causing errors like this to get thrown:

    error: db5 error(-30973) from dbenv->open: BDB0087 DB_RUNRECOVERY:
    Fatal error, run database recovery

Fixes https://issues.redhat.com/browse/OCPBUGS-6505