remove 4.10 aws-ovn-windows presubmit job (#49274)
this job is permafailing with some issue with the test getting
the Windows AMI:

=== RUN   TestWMCO
    wmco_test.go:36:
        	Error Trace:	wmco_test.go:36
        	Error:      	Received unexpected error:
        	            	error obtaining aws interface object: unable to get latest Windows AMI: found zero images matching given filter: {
        	            	  Name: "name",
        	            	  Values: ["Windows_Server-2019-English-Full-ContainersLatest-????.??.??"]
        	            	}
        	            	cloud provider creation failed
        	            	github.com/openshift/windows-machine-config-operator/test/e2e.NewTestContext
        	            		/go/src/github.com/openshift/windows-machine-config-operator/test/e2e/main_test.go:96
        	            	github.com/openshift/windows-machine-config-operator/test/e2e.TestWMCO
        	            		/go/src/github.com/openshift/windows-machine-config-operator/test/e2e/wmco_test.go:35
        	            	testing.tRunner
        	            		/usr/lib/golang/src/testing/testing.go:1259
        	            	runtime.goexit
        	            		/usr/lib/golang/src/runtime/asm_amd64.s:1581
        	Test:       	TestWMCO
--- FAIL: TestWMCO (0.24s)
FAIL

Since this is a pretty old release, let's just remove job and not waste
cloud resources on something that we know will fail.

Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>