fix e2e cluster-api-provider-libvirt tests for 4.8
This applies the changes from the commit below to the 4.8 presubmit
file. The 4.9/4.10/master files already have the same changes as 4.7

commit 03193199c3737ff67f771f07be57cb4eab4c5483
Author: Prashanth Sundararaman <psundara@redhat.com>
Date:   Mon Mar 15 10:54:35 2021 -0400

    fix e2e cluster-api-provider-libvirt tests for 4.7

    e2e-libvirt jobs in the 4.7 branch are failing with:

    ```
    gcloud compute --project openshift-gce-devel-ci ssh --zone us-east1-c packer@ci-op-s8btqkkv-4e104 --command 'export KUBECONFIG=/home/packer/clusters/installer/auth/kubeconfig && /home/packer/run-tests.sh'
    openshift-tests version: v4.1.0-3593-g98a759f
    error: suite "files" does not contain any tests
    ```

    We have seen it in the past when there were no tests in the suite this error is thrown