WIP: use centos-stream9 base images for failing images
When using centos stream8 base images, we see this error:
```
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```
looks like some issue accessing the centos stream8 mirrorlist. switching to centos-stream9.