Fix Z jobs by defining REMOTE_LIBVIRT_HOSTNAME_2
A new cluster was introduced for Power but not Z. Still, the hostname
needs to be defined because "" is not a valid hostname, causing the
following failure in CI:

error: some steps failed:
  * could not run steps: step e2e-remote-libvirt failed: could not wait for template instance to be ready: failed to create objects: Pod "e2e-remote-libvirt" is invalid: spec.hostAliases.hostnames: Invalid value: "": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>