NO-JIRA: cincinnati: bump to ubi9 everywhere (#62815)
* NO-JIRA: cincinnati: bump to ubi9 everywhere

* Bump python 3.8 to 3.9

From the rehearsal [1]:
```
Error: Unable to find a match: python38
```
and it seems python3 is 3.9 on ubi9 [2].

[1]. https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/62815/rehearse-62815-pull-ci-openshift-cincinnati-master-images/1902022265147494400

[2]. https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/installing_and_using_dynamic_programming_languages/assembly_installing-and-using-python_installing-and-using-dynamic-programming-languages#assembly_installing-and-using-python_installing-and-using-dynamic-programming-languages

* Install pip

This PR removed the installation of python3 because it has been installed on the base image
as shown by the build log [1]:

```
...
Package python3-3.9.21-1.el9_5.x86_64 is already installed.
...
STEP 10/15: RUN pip3 install --user yamllint
/bin/sh: line 1: pip3: command not found
...
```

In addition, we have to install pip [2] to address the error in the rehearsal [1].

[1]. https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/62815/rehearse-62815-pull-ci-openshift-cincinnati-master-images/1902037142339588096

[2]. https://pip.pypa.io/en/stable/installation/