Add ingress DNS entries to make live-iso conformance tests pass (#31685)
Trying to fix conformance tests failing on:

```
Shutting down SimultaneousPodIPControllerSimultaneousPodIPController
shut downSuite run returned error: AlertErr: Thanos queriers not
connected to all Prometheus sidecars: Post
"https://thanos-querier-openshift-monitoring.apps.test-infra-cluster.redhat.com/api/v1/query":
dial tcp: lookup
thanos-querier-openshift-monitoring.apps.test-infra-cluster.redhat.com
on 147.75.207.207:53: no such host
error: AlertErr: Thanos queriers not connected to all Prometheus
sidecars: Post
"https://thanos-querier-openshift-monitoring.apps.test-infra-cluster.redhat.com/api/v1/query":
dial tcp: lookup
thanos-querier-openshift-monitoring.apps.test-infra-cluster.redhat.com
on 147.75.207.207:53: no such host
```

It only seems required for 4.12 jobs:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/31590/rehearse-31590-periodic-ci-openshift-release-master-nightly-4.12-e2e-metal-ovn-single-node-live-iso/1561975528968163328