ci-operator/step-registry/gather/gcp-console: Gather console logs on GCP
Like the similar aws-console step, but for GCP, following [1].  I'm
not sure why they require a --zone argument when 'instances list'
seems to be able to figure this out, but whatever.  Leaving it off
doesn't seem to be an option:

  wking@cloudshell:~ (openshift-gce-devel-ci)$ gcloud --format json compute instances get-serial-port-output "${INSTANCE_ID}" </dev/null >logs.json
  ERROR: (gcloud.compute.instances.get-serial-port-output) Underspecified resource [ci-ln-2gtd6db-f76d1-fj4cl-master-0]. Specify the [--zone] flag.
  wking@cloudshell:~ (openshift-gce-devel-ci)$ gcloud --version | head -n1
  Google Cloud SDK 315.0.0

OWNERS are like AWS, from 3ff8e696c5 (gather/aws/console: Add a step
to gather console logs on AWS, 2020-06-17, #9743), and also the
installer's GCP approvers [2].

[1]: https://cloud.google.com/compute/docs/reference/rest/v1/instances/getSerialPortOutput
[2]: https://github.com/openshift/installer/blob/e17697302ff991ae80d6e9c0c10426db510881e2/OWNERS_ALIASES#L60-L62