aws-load-balancer-operator: Skip creation of deprecated waf-regional (WAF Classic) Web ACL (#65982)
This commit prevents OCPBUGS-57320.

https://issues.redhat.com//browse/OCPBUGS-57320

aws-load-balancer-operator e2e tests were failing permanently with
the following message on the attempt to create aws waf regional acl:
WAFBadRequestException: AWS WAF Classic (v1) support will end on September 30, 2025.
Effective May 1st, 2025, the creation of new WebACL v1 is no longer permitted.

Until the support of WAF Classic API is not deprecated in ALBO API
the creation of WAF Classic resources within the pre-install steps
of the ROSA install workflow are skipped to mitigate permanent CI failures.

* ci-operator/step-registry/aws-load-balancer/pre-install-rosa/aws-load-balancer-pre-install-rosa-commands.sh:
Add variable SKIP_WAF_WEB_ACL_CREATION and conditional logic
to skip pre-install creation of aws waf regional acl if its set to true.