Revert "installer smoke_tests use LOCAL_IMAGE for optional installer-smoke image"
This reverts commit 50a23965c6490f713a67e4d28acdbd1d8be1a2ee, #1517.

It was giving us [1]:

  error: could not run steps: template e2e-aws-smoke has required
  parameter LOCAL_IMAGE_INSTALLER_SMOKE which is not defined

and we're not clear on why.  Reverting it helps unblock the installer
merge queue while we figure it out.

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/252/pull-ci-openshift-installer-e2e-aws-smoke/115/build-log.txt