installer: remove ineffective test skip for azurestack (#35263)
The skip is causing
```
Skipping tests:
Error: no tests were found matching the TEST_SKIPS regex:
provisioning should provision storage with pvc data source in parallel
```
but the test doesn't seem to exist anymore:

```
[origin]$: ./openshift-tests run --dry-run openshift/conformance/parallel --run "provisioning should provision storage with pvc data source in parallel"
Jan 10 13:15:48.603: INFO: Enabling in-tree volume drivers
Suite run returned error: suite "openshift/conformance/parallel" does not contain any tests
```