oc-mirror: bump golangci-lint version (#67020)
We need a version built with Golang 1.24 so the CI tests won't fail with
```
Error: can't load config: the Go language version (go1.23) used to build golangci-lint is lower than the targeted Go version (1.24.0)
Failed executing command with error: can't load config: the Go language version (go1.23) used to build golangci-lint is lower than the targeted Go version (1.24.0)
```