OpenStack: make clouds to env script python 27 compatible
Release 4.5 still uses python 2.7 and it's causing the script to fail
with:

 Traceback (most recent call last):
  File "<string>", line 32, in <module>
  File "<string>", line 24, in parse_key
 AttributeError: 'module' object has no attribute 'quote'

This commit imports quote from the pipes module if it can't find it in
the shlex one.

Also removed a non-ascii character that might break in a container that
doesn't have utf8 locales.