ci-operator/step-registry/openshift/e2e/aws/proxy: Tear down proxy post-gather
Remove the ipi-aws-post-proxy chain, because it's only consumed by
this one workflow, so the indirection isn't useful.  Explicitly
including the steps in the workflow allows us to:

* Keep the gather-aws-console early, where it's more likely to have
  access to console logs for machines which may have booted a while
  ago.

* Move gather-proxy after the vanilla gather chain, so we have proxy
  logs for the traffic that happens during those (e.g. pulling down
  must-gather images).

* Move ipi-deprovision-proxy after the vanilla gather chain, so we
  have access to the must-gather images instead of timing out with:

    $ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.6-e2e-aws-proxy/1309839473399304192/artifacts/e2e-aws-proxy/gather-extra/nodes/ip-10-0-60-233.us-west-1.compute.internal/journal | gunzip | grep 'must-gather.*proxyconnect' | tail -n1
    Sep 26 14:47:59.098617 ip-10-0-60-233 hyperkube[1485]: I0926 14:47:59.098506    1485 status_manager.go:572] Status for pod "must-gather-vhffs_openshift-must-gather-4847p(a99fdc6b-03af-43de-88a8-ca1a73d89b88)" updated successfully: (2, {Phase:Pending Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-09-26 14:46:56 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-09-26 14:46:56 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [gather copy]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-09-26 14:46:56 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [gather copy]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-09-26 14:46:56 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.0.60.233 PodIP:10.128.2.165 PodIPs:[{IP:10.128.2.165}] StartTime:2020-09-26 14:46:56 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:copy State:{Waiting:&ContainerStateWaiting{Reason:ImagePullBackOff,Message:Back-off pulling image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:33485bb4fd1f7c442f3d95f7326d8a84ea0f450d10c4268f488b0a44fedd3a72",} Running:nil Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:33485bb4fd1f7c442f3d95f7326d8a84ea0f450d10c4268f488b0a44fedd3a72 ImageID: ContainerID: Started:0xc0039f40cd} {Name:gather State:{Waiting:&ContainerStateWaiting{Reason:ErrImagePull,Message:rpc error: code = Unknown desc = error pinging docker registry quay.io: Get "https://quay.io/v2/": proxyconnect tcp: dial tcp 10.0.3.16:3128: i/o timeout,} Running:nil Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:33485bb4fd1f7c442f3d95f7326d8a84ea0f450d10c4268f488b0a44fedd3a72 ImageID: ContainerID: Started:0xc0039f40ce}] QOSClass:BestEffort EphemeralContainerStatuses:[]})

  which had been failing the [1]:

    Run multi-stage test e2e-aws-proxy - e2e-aws-proxy-gather-must-gather container test

  test-case with:

    Running must-gather...
    error: gather did not start for pod must-gather-vhffs: unable to pull image: ImagePullBackOff: Back-off pulling image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:33485bb4fd1f7c442f3d95f7326d8a84ea0f450d10c4268f488b0a44fedd3a72"

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.6-e2e-aws-proxy/1309839473399304192