Prowjob CRD: Make manifest pass --validate
Fixes:
```
ERRO[0167] oc apply -f clusters/app.ci/prow/01_crd/admin_01_prowjob_crd.yaml --as system:admin --context app.ci --dry-run=server --validate=true: failed to apply
error: error validating "clusters/app.ci/prow/01_crd/admin_01_prowjob_crd.yaml": error validating data: [
  ValidationError(CustomResourceDefinition.spec): unknown field "additionalPrinterColumns" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec,
  ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec,
  ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec,
  ValidationError(CustomResourceDefinition.spec): missing required field "versions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec];
if you choose to ignore these errors, turn validation off with --validate=false
```

-> CRD manifests have `versions` which contains both `schema`
(previously in `validation`) and additional column definitions.