Make IS & BuildConfig manifests valid
Fixes things like:
```
ERRO[0685] oc apply -f clusters/app.ci/supplemental-ci-images/validation-images/shellcheck/shellcheck.yaml --as system:admin --context app.ci --dry-run=server --validate=true: failed to apply
error: error validating "clusters/app.ci/supplemental-ci-images/validation-images/shellcheck/shellcheck.yaml": error validating data: [
  ValidationError(BuildConfig.spec.source): missing required field "type" in com.github.openshift.api.build.v1.BuildSource,
  ValidationError(BuildConfig.spec.strategy): missing required field "type" in com.github.openshift.api.build.v1.BuildStrategy];
if you choose to ignore these errors, turn validation off with --validate=false
```