Export BUNDLE_STORAGE_IMG var
In Pr[1] we are Spliting out openstack-storage-bundle from meta
operator. Operarot image build is currently failing with below error
because BUNDLE_STORAGE_IMG  is not set properly, logs here: [2]

~~~
[14/16] STEP 1/1: FROM quay.io//openstack-operator-storage-bundle:v0.0.1 AS openstack-storage-bundle
[15/16] STEP 1/19: FROM golang:1.19 AS merger
[15/16] STEP 2/19: WORKDIR /workspace
Error shutting down storage: A layer is mounted: layer is in use by a container
error: build error: error creating build container: invalid reference format
~~~

The value of following vars are below as per[3]:-
~~~
BUNDLE_STORAGE_IMG ?= $(IMAGE_TAG_BASE)-storage-bundle:v$(VERSION)
IMAGE_TAG_BASE ?= quay.io/$(USER)/openstack-operator
~~~
and because $USER was not set in prow job we got `quay.io//openstack-operator-storage-bundle:v0.0.1`

We set IMAGE_TAG_BASE in prow step[4] but it was not exported that's
 why IMAGE_TAG_BASE  value came from Makefile default.

we can add `BUNDLE_STORAGE_IMG` value in build step here similar to what we did in
create_bundle.sh already[5]

[1] https://github.com/openstack-k8s-operators/openstack-operator/pull/260
[2] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_openstack-operator/260/pull-ci-openstack-k8s-operators-openstack-operator-master-openstack-operator-build-deploy/1641630279204343808/artifacts/openstack-operator-build-deploy/openstack-k8s-operators-build/build-log.txt
[3] https://github.com/openstack-k8s-operators/openstack-operator/blob/991824fa0bb01249ec123ff411744be15fe8454e/Makefile#L32-L37
[4] https://github.com/openshift/release/blob/master/ci-operator/step-registry/openstack-k8s-operators/build/openstack-k8s-operators-build-commands.sh#L57
[5] https://github.com/openstack-k8s-operators/openstack-operator/blob/991824fa0bb01249ec123ff411744be15fe8454e/.github/create_bundle.sh#L26