Add 'error:' highlight to spyglass
When `oc` fails to mirror images, which is something we see in the
metal-ipi job, it reports:

```
info: Mirroring completed in 58.09s (113.5MB/s)
error: one or more errors occurred while uploading images
```