openstack: remove some skipped tests
Some tests were skipped but are now disabled, so we need to remove them
from the TEST_SKIPS or `openshift-tests` will fail with this error:

```
Error: no tests were found matching the TEST_SKIPS regex
```