ci-operator: Fix Prometheus gather in absence of PVCs
Avoid failures like [1]:

  $ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.8-upgrade-from-stable-4.7-e2e-gcp-upgrade/1461391694523011072/artifacts/e2e-gcp-upgrade/gather-extra/build-log.txt | grep 'prometheus-k8s-1 *7'
  oc --insecure-skip-tls-verify exec -n openshift-monitoring prometheus-k8s-1   7/7     Running   1          29m -- tar cvzf - -C /prometheus .
  oc --insecure-skip-tls-verify exec -n openshift-monitoring prometheus-k8s-1   7/7     Running   1          29m -- /bin/bash -c curl -G http://localhost:9090/api/v1/targets/metadata --data-urlencode 'match_target={instance!=""}'
  oc --insecure-skip-tls-verify exec -n openshift-monitoring prometheus-k8s-1   7/7     Running   1          29m -- /bin/bash -c curl -G http://localhost:9090/api/v1/status/config
  oc --insecure-skip-tls-verify exec -n openshift-monitoring prometheus-k8s-1   7/7     Running   1          29m -- /bin/bash -c curl -G http://localhost:9090/api/v1/status/tsdb
  oc --insecure-skip-tls-verify exec -n openshift-monitoring prometheus-k8s-1   7/7     Running   1          29m -- /bin/bash -c curl -G http://localhost:9090/api/v1/status/runtimeinfo
  oc --insecure-skip-tls-verify exec -n openshift-monitoring prometheus-k8s-1   7/7     Running   1          29m -- /bin/bash -c curl -G http://localhost:9090/api/v1/targets
  error: the server doesn't have a resource type "prometheus-k8s-1   7"
  error: the server doesn't have a resource type "prometheus-k8s-1   7"
  error: the server doesn't have a resource type "prometheus-k8s-1   7"
  error: the server doesn't have a resource type "prometheus-k8s-1   7"
  error: the server doesn't have a resource type "prometheus-k8s-1   7"
  error: the server doesn't have a resource type "prometheus-k8s-1   7"

These slipped in with d70666d64bf (Snapshot oldest prometheus data
(#22698), 2021-11-03), where we confirmed that the with-PVC case
worked, but hadn't checked the without-PVC case.

Also drop the =true from --ignore-not-found, because setting the value
true is the implicit behavior.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.8-upgrade-from-stable-4.7-e2e-gcp-upgrade/1461391694523011072