hack/ensure_job_cluster: Write error messages without tracebacks
Because [1]:

  2020-04-15 17:51:28,100:INFO:checking jobs ...
  multiprocessing.pool.RemoteTraceback:
  """
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
      result = (True, func(*args, **kwds))
    File "./hack/ensure_job_cluster.py", line 112, in process_file
      .format(file_path, name_map))
  Exception: those jobs in ./ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.18-presubmits.yaml have to run on the cluster {'pull-ci-cri-o-cri-o-release-1.18-e2e-aws': 'api.ci', 'pull-ci-cri-o-cri-o-release-1.18-images': 'api.ci', 'pull-ci-cri-o-cri-o-release-1.18-launch-aws': 'api.ci'}
  """
  The above exception was the direct cause of the following exception:
  Traceback (most recent call last):
    File "./hack/ensure_job_cluster.py", line 145, in <module>
      main()
    File "./hack/ensure_job_cluster.py", line 139, in main
      ensure(args.job_dir, args.overwrite, args.processes)
    File "./hack/ensure_job_cluster.py", line 94, in ensure
      for _ in pool.imap_unordered(process_file, args):
    File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 748, in next
      raise value
  Exception: those jobs in ./ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.18-presubmits.yaml have to run on the cluster {'pull-ci-cri-o-cri-o-release-1.18-e2e-aws': 'api.ci', 'pull-ci-cri-o-cri-o-release-1.18-images': 'api.ci', 'pull-ci-cri-o-cri-o-release-1.18-launch-aws': 'api.ci'}

is a bit intimidating, and takes some thinking to decide that it's the
script successfully complaining about an underlying issue, and not
falling over because of some script-internal issue.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/8322/pull-ci-openshift-release-master-generated-cluster/2624