ci-operator/config/openshift/release: Drop cross-minor rollback jobs (#39897)
* ci-operator/config/openshift/release: Drop cross-minor rollback jobs

The job flavor was originally added in 083763496f (Add
ovn-upgrade-rollback job for 4.7->4.8, 2021-02-24, #16260).  The jobs
have subsequently been cloned forward to new minors as part of the
branching process.  And as older jobs started failing, I'd been
dropping them gradually like 856aab20df
(ci-operator/config/openshift/release/openshift-release-master__ci-4.11-upgrade-from-stable-4.10:
Drop failing rollback jobs, 2022-10-11, #33005).  But rounding with
Jamo, the jobs no longer serve a useful role, and as 856aab20df points
out, rollbacks between minor releases are not supported.  Drop the
likely-to-fail and not-useful-even-when-it-passes jobs in their
entirety, so they stop getting cloned forward during branching.

I'm also adjusting the release controller changes from 421c921686
(Introducing Rollback informing jobs, 2023-05-19, #39488).  I'm
dropping 4.12 and earlier rollback informers, so we can focus on 4.13
while we feel out the new process.  And I'm pivoting 4.13 away from
the cross-minor job that this pull request drops, and towards the
rollback-oldest-supported job that will help back [1].

[1]: https://issues.redhat.com/browse/OTA-455

* hack/validate-release-controller-config: Supplemental Git diff

Because [1]:

  ERROR: The following differences were found:
  3a4
  > 03c544e5d55a55ae9f19d0de7d786341  .//core-services/release-controller/_releases/priv/release-ocp-4.12.json
  35d35
  < 1826a1b520574b66f152f814811c19f6  .//core-services/release-controller/_releases/priv/release-ocp-4.13.json
  42a43
  ...

tells me what files need changing, but not what changes to make to them.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/39897/pull-ci-openshift-release-master-release-controller-config/1664331471080394752

---------

Co-authored-by: wking <wking@penguin>