hack/validate-release-controller-config: Supplemental Git diff
Because [1]:

  ERROR: The following differences were found:
  3a4
  > 03c544e5d55a55ae9f19d0de7d786341  .//core-services/release-controller/_releases/priv/release-ocp-4.12.json
  35d35
  < 1826a1b520574b66f152f814811c19f6  .//core-services/release-controller/_releases/priv/release-ocp-4.13.json
  42a43
  ...

tells me what files need changing, but not what changes to make to them.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/39897/pull-ci-openshift-release-master-release-controller-config/1664331471080394752