ci-operator: update libvirt job
The e2e-libvirt job has been broken for cluster-api-provider-libvirt a
little while with the following:

    error: suite "files" does not contain any tests

I just copied the tests over from the installer's job. This should be
cleaned up into a template so that these definitions don't fall out of
sync again.