appliance: update to stream9
Updated base image to stream9 in appliance config.
iinm, this should solve the following error when
using 'dnf install' on image build:
```
CentOS Stream 8 - AppStream                      74  B/s |  38  B     00:00
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```
See build log:
https://storage.googleapis.com/test-platform-results/pr-logs/pull/openshift_appliance/245/pull-ci-openshift-appliance-master-images/1800128692949618688/build-log.txt