OpenStack: prevent unbound variable in get_clouds_param()
This presumably causes the cinder tests to fail with:

  ERROR: You must provide a password through --os-password, env[OS_PASSWORD] or, prompted response.