RHOAIENG-19051: chore(opendatahub-io/notebooks): switch image tests from `ipi-gcp` to run on `hypershift-hostedcluster-workflow`
* make jobs
* make ci-operator-config

Various error messages encountered while working on the PR

```
ERROR[2025-03-06T12:19:30Z]
  * could not run steps: step notebooks-ubi9-e2e-tests failed: "notebooks-ubi9-e2e-tests" test steps failed: could not determine image pull spec for image jupyter-pytorch-ubi9-python-3.11 on step cuda-jupyter-pt-ubi9-python-3-11-test-e2e
INFO[2025-03-06T12:19:30Z] Reporting job state 'failed' with reason 'executing_graph:step_failed:utilizing_lease:executing_test:executing_multi_stage_test'
```

```
Error: failed to create infra: hosted zone hypershift.aws-2.ci.openshift.org not found
failed to create infra: hosted zone hypershift.aws-2.ci.openshift.org not found
```

```
could not load configuration from candidate revision of release repo: failed to load ci-operator configuration from release repo: invalid ci-operator config: invalid configuration: tests[36].cluster_claim.cloud cannot be empty when cluster_claim is not nil
```

`CONTROL_PLANE_NODE_SELECTOR: kubernetes.io/arch=amd64` does not work:

```
Run multi-stage test notebooks-ubi9-e2e-tests - notebooks-ubi9-e2e-tests-hypershift-hostedcluster-dump-hostedcluster container test expand_less	5s
{  /github.com/spf13/cobra/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	/hypershift/vendor/github.com/spf13/cobra/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext
	/hypershift/vendor/github.com/spf13/cobra/command.go:1032
main.main
	/hypershift/main.go:78
runtime.main
	/usr/lib/golang/src/runtime/proc.go:267
2025-03-05T14:46:38Z	ERROR	Failed to dump guest cluster	{"error": "failed to get hosted cluster clusters/ccba682d5430be280564: hostedclusters.hypershift.openshift.io \"ccba682d5430be280564\" not found"}
github.com/openshift/hypershift/cmd/cluster/core.DumpCluster
	/hypershift/cmd/cluster/core/dump.go:381
github.com/openshift/hypershift/cmd/cluster/core.NewDumpCommand.func1
	/hypershift/cmd/cluster/core/dump.go:126
github.com/spf13/cobra.(*Command).execute
	/hypershift/vendor/github.com/spf13/cobra/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
	/hypershift/vendor/github.com/spf13/cobra/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	/hypershift/vendor/github.com/spf13/cobra/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext
	/hypershift/vendor/github.com/spf13/cobra/command.go:1032
main.main
	/hypershift/main.go:78
runtime.main
	/usr/lib/golang/src/runtime/proc.go:267
2025-03-05T14:46:38Z	INFO	Archiving dump	{"command": "tar", "args": ["-cvzf", "hypershift-dump.tar.gz", "aggregated-discovery-api.yaml", "aggregated-discovery-apis.yaml", "event-filter.html", "network_logs", "timestamp"]}
2025-03-05T14:46:38Z	INFO	Successfully archived dump	{"duration": "9.165078ms"}
Collect minimal required cluster information
Error from server (NotFound): hostedclusters.hypershift.openshift.io "ccba682d5430be280564" not found
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:84","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2025-03-05T14:46:38Z"}
error: failed to execute wrapped command: exit status 1
}
: Run multi-stage test post phase expand_less	1m39s
{  ["notebooks-ubi9-e2e-tests" pod "notebooks-ubi9-e2e-tests-hypershift-hostedcluster-dump-hostedcluster" failed: could not watch pod: the pod ci-op-8i6v3mj6/notebooks-ubi9-e2e-tests-hypershift-hostedcluster-dump-hostedcluster failed after 14s (failed containers: test): ContainerFailed one or more containers exited

Container test exited with code 1, reason Error
---
/github.com/spf13/cobra/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	/hypershift/vendor/github.com/spf13/cobra/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext
	/hypershift/vendor/github.com/spf13/cobra/command.go:1032
main.main
	/hypershift/main.go:78
runtime.main
	/usr/lib/golang/src/runtime/proc.go:267
2025-03-05T14:46:38Z	ERROR	Failed to dump guest cluster	{"error": "failed to get hosted cluster clusters/ccba682d5430be280564: hostedclusters.hypershift.openshift.io \"ccba682d5430be280564\" not found"}
github.com/openshift/hypershift/cmd/cluster/core.DumpCluster
	/hypershift/cmd/cluster/core/dump.go:381
github.com/openshift/hypershift/cmd/cluster/core.NewDumpCommand.func1
	/hypershift/cmd/cluster/core/dump.go:126
github.com/spf13/cobra.(*Command).execute
	/hypershift/vendor/github.com/spf13/cobra/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
	/hypershift/vendor/github.com/spf13/cobra/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	/hypershift/vendor/github.com/spf13/cobra/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext
	/hypershift/vendor/github.com/spf13/cobra/command.go:1032
main.main
	/hypershift/main.go:78
runtime.main
	/usr/lib/golang/src/runtime/proc.go:267
2025-03-05T14:46:38Z	INFO	Archiving dump	{"command": "tar", "args": ["-cvzf", "hypershift-dump.tar.gz", "aggregated-discovery-api.yaml", "aggregated-discovery-apis.yaml", "event-filter.html", "network_logs", "timestamp"]}
2025-03-05T14:46:38Z	INFO	Successfully archived dump	{"duration": "9.165078ms"}
Collect minimal required cluster information
Error from server (NotFound): hostedclusters.hypershift.openshift.io "ccba682d5430be280564" not found
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:84","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2025-03-05T14:46:38Z"}
error: failed to execute wrapped command: exit status 1
---
Link to step on registry info site: https://steps.ci.openshift.org/reference/hypershift-hostedcluster-dump-hostedcluster
Link to job on registry info site: https://steps.ci.openshift.org/job?org=opendatahub-io&repo=notebooks&branch=main&test=notebooks-ubi9-e2e-tests, "notebooks-ubi9-e2e-tests" pod "notebooks-ubi9-e2e-tests-hypershift-hostedcluster-destroy-hostedcluster" failed: could not watch pod: the pod ci-op-8i6v3mj6/notebooks-ubi9-e2e-tests-hypershift-hostedcluster-destroy-hostedcluster failed after 1m8s (failed containers: test): ContainerFailed one or more containers exited

Container test exited with code 1, reason Error
---
+ echo 'Set KUBECONFIG to management cluster'
Set KUBECONFIG to management cluster
+ export KUBECONFIG=/var/run/hypershift-workload-credentials/kubeconfig
+ KUBECONFIG=/var/run/hypershift-workload-credentials/kubeconfig
+ DEFAULT_BASE_DOMAIN=ci.hypershift.devcluster.openshift.com
+ [[ aws == \a\w\s ]]
+ AWS_GUEST_INFRA_CREDENTIALS_FILE=/var/run/secrets/ci.openshift.io/cluster-profile/.awscred
+ [[ ! -f /var/run/secrets/ci.openshift.io/cluster-profile/.awscred ]]
+ [[ false == \t\r\u\e ]]
+ DOMAIN=ci.hypershift.devcluster.openshift.com
+ HOSTED_CLUSTER_FILE=/tmp/secret/hosted_cluster.txt
+ '[' -f /tmp/secret/hosted_cluster.txt ']'
+ echo 'Loading /tmp/secret/hosted_cluster.txt'
Loading /tmp/secret/hosted_cluster.txt
+ source /tmp/secret/hosted_cluster.txt
++ CLUSTER_NAME=ccba682d5430be280564
++ INFRA_ID=547bb
+ echo 'Loaded /tmp/secret/hosted_cluster.txt'
Loaded /tmp/secret/hosted_cluster.txt
+ echo 'Cluster name: ccba682d5430be280564, infra ID: 547bb'
Cluster name: ccba682d5430be280564, infra ID: 547bb
++ oc -n clusters get hostedclusters ccba682d5430be280564 -o 'jsonpath={.metadata.annotations.created-at}'
Error from server (NotFound): hostedclusters.hypershift.openshift.io "ccba682d5430be280564" not found
+ createdAt=
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:84","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2025-03-05T14:47:54Z"}
error: failed to execute wrapped command: exit status 1
---
Link to step on registry info site: https://steps.ci.openshift.org/reference/hypershift-hostedcluster-destroy-hostedcluster
Link to job on registry info site: https://steps.ci.openshift.org/job?org=opendatahub-io&repo=notebooks&branch=main&test=notebooks-ubi9-e2e-tests]}
```