Move packet-check jobs to a separate variant
This change puts packet-check jobs that are used to handle
"garbage-collection" of Equinix machines to a separate and new variant.

The idea is removing as much dependencies as we can from this process,
because sometimes we have problems like:
```
error: unable to parse image
registry.build03.ci.openshift.org/ci-op-8274ip44/stable@sha256:b2eb90c0e1d661307768f7ff85487927412ea78502a8a8ab30b513f48dc91340:
cannot retrieve image configuration for manifest
sha256:b2eb90c0e1d661307768f7ff85487927412ea78502a8a8ab30b513f48dc91340:
received unexpected HTTP status: 500 Internal Server Error
```

(see
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-test-infra-master-assisted-packet-check/1546902353360195584)

The ``releases`` stanza cannot be moved, so instead I just tried
minimizing it to one release item.