OpenStack: rename Smoke to Early
In origin commit 07bef47, the `Smoke` tests were renamed to `Early`,
causing the `run-minimal-tests()` function to fail with:

  error: suite "files" does not contain any tests

The same fix should be ported to oVirt platform.