fix(build): bumps golang builder to go1.25
odh-operator needs go1.25 as it is built as part of test setup script

Related error:

```
 go: go.mod requires go >= 1.25 (running go 1.24.6; GOTOOLCHAIN=local)
go: go.mod requires go >= 1.25 (running go 1.24.6; GOTOOLCHAIN=local)
go: go.mod requires go >= 1.25 (running go 1.24.6; GOTOOLCHAIN=local)
/tmp/tmp.hJFz3jkzpA/opendatahub-operator/bin/controller-gen --load-build-tags=odh rbac:roleName=controller-manager-role crd:ignoreUnexportedFields=true webhook paths="./..." output:crd:artifacts:config=config/crd/bases output:rbac:artifacts:config=config/rbac output:webhook:artifacts:config=config/webhook
Error: load packages in root "/tmp/tmp.hJFz3jkzpA/opendatahub-operator": err: exit status 1: stderr: go: go.mod requires go >= 1.25 (running go 1.24.6; GOTOOLCHAIN=local)
```

Ref: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/opendatahub-io_maas-billing/299/pull-ci-opendatahub-io-maas-billing-main-e2e-test-maas-api/1999443848702464000#1:build-log.txt%3A196

Signed-off-by: Bartosz Majsak <bartosz.majsak@gmail.com>