hack/step-jobs-by-platform: Adjust to jobs with no workflow
Avoiding:

  KeyError: "no workflow in pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted: {'platform': 'metal', 'post': [{'ref': 'baremetalds-packet-teardown'}], 'cluster_profile': 'packet', 'pre': [{'ref': 'baremetalds-packet-setup'}, {'ref': 'ipi-install-rbac'}, {'ref': 'baremetalds-assisted-setup'}]}"

Due to the workflow-less job from 78f16dacac (Run assisted-test-infra
with an empty test list, 2020-08-04, #10667).